/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cde.view;

import br.com.cde.connection.ConnectionFactoryCreateBd;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author alafaria
 */
public class TelaCriacaoBancoDados extends javax.swing.JFrame {

    private Statement st;
    private Connection con;

    /**
     * Creates new form TelaCriacaoBancoDados
     */
    public TelaCriacaoBancoDados() {
        initComponents();
        setIconImage(getToolkit().createImage(getClass().getResource("/icones/stock.png")));
        this.con = new ConnectionFactoryCreateBd().getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btCriarBanco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criação de Banco de Dados");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Criação de Banco de Dados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText(", esta ação irá criar o banco de dados da aplicação.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("CUIDADO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tem certeza que deseja continuar?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Esta ação pode refletir no bom funcionamento da aplicação.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Em caso de dúvidas, consulte o desenvolvedor.");

        btCriarBanco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCriarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/bd.png"))); // NOI18N
        btCriarBanco.setText("Criar Banco de Dados");
        btCriarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarBancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btCriarBanco)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(btCriarBanco)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCriarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarBancoActionPerformed
        // TODO add your handling code here:
        try {
            st = con.createStatement();

            st.execute("create database controle_estoque");

            st.execute("use controle_estoque");

            st.execute("CREATE TABLE tabela_usuario (\n"
                    + "codigo_usuario int(11) NOT NULL AUTO_INCREMENT,\n"
                    + "nome_usuario varchar(45) DEFAULT NULL,\n"
                    + "email_usuario varchar(45) DEFAULT NULL,\n"
                    + "login_usuario varchar(45) DEFAULT NULL,\n"
                    + "senha_usuario varchar(45) DEFAULT NULL,\n"
                    + "lembrete_senha_usuario varchar(45) DEFAULT NULL,\n"
                    + "permissao_acesso_usuario varchar(45) DEFAULT NULL,\n"
                    + "PRIMARY KEY (codigo_usuario)\n"
                    + ");");

            st.execute("insert into tabela_usuario (nome_usuario, email_usuario, login_usuario, senha_usuario, lembrete_senha_usuario, permissao_acesso_usuario) values ('Administrador', 'adm@gmail.com', 'admin', 'admin', 'adm do sistema', 'Administrador')");

            st.execute("CREATE TABLE tabela_tipo (\n"
                    + "  codigo_tipo int(11) NOT NULL AUTO_INCREMENT,\n"
                    + "  tipo_tipo varchar(45) DEFAULT NULL,\n"
                    + "  descricao_tipo varchar(45) DEFAULT NULL,\n"
                    + "  PRIMARY KEY (codigo_tipo)\n"
                    + ")");

            st.execute("insert into tabela_tipo (tipo_tipo, descricao_tipo) values ('Vestimenta','Vestimenta')");
            st.execute("insert into tabela_tipo (tipo_tipo, descricao_tipo) values ('Calçados','Calçados')");
            st.execute("insert into tabela_tipo (tipo_tipo, descricao_tipo) values ('Acessórios','Acessórios')");
            st.execute("insert into tabela_tipo (tipo_tipo, descricao_tipo) values ('Utensílios','Utensilios')");

            st.execute("CREATE TABLE tabela_tamanho (\n"
                    + "  codigo_tamanho int(11) NOT NULL AUTO_INCREMENT,\n"
                    + "  tamanho_tamanho varchar(45) DEFAULT NULL,\n"
                    + "  descricao_tamanho varchar(45) DEFAULT NULL,\n"
                    + "  PRIMARY KEY (codigo_tamanho)\n"
                    + ")");

            st.execute("insert into tabela_tamanho (tamanho_tamanho, descricao_tamanho) values ('P','Tamanho Pequeno');");
            st.execute("insert into tabela_tamanho (tamanho_tamanho, descricao_tamanho) values ('M','Tamanho Médio');");
            st.execute("insert into tabela_tamanho (tamanho_tamanho, descricao_tamanho) values ('G','Tamanho Grande');");

            st.execute("CREATE TABLE tabela_produto (\n"
                    + "  codigo_produto int(11) NOT NULL AUTO_INCREMENT,\n"
                    + "  nome_produto varchar(45) DEFAULT NULL,\n"
                    + "  descricao_produto varchar(45) DEFAULT NULL,\n"
                    + "  tamanho_produto varchar(45) DEFAULT NULL,\n"
                    + "  valor_produto double DEFAULT NULL,\n"
                    + "  lote_produto varchar(45) DEFAULT NULL,\n"
                    + "  tipo_produto varchar(45) DEFAULT NULL,\n"
                    + "  categoria_produto varchar(45) DEFAULT NULL,\n"
                    + "  quantidade_produto int(11) DEFAULT NULL,\n"
                    + "  data_produto date DEFAULT NULL,\n"
                    + "  PRIMARY KEY (codigo_produto)\n"
                    + ")");

            st.execute("CREATE TABLE tabela_lote (\n"
                    + "  codigo_lote int(11) NOT NULL AUTO_INCREMENT,\n"
                    + "  lote_lote varchar(45) DEFAULT NULL,\n"
                    + "  descricao_lote varchar(45) DEFAULT NULL,\n"
                    + "  PRIMARY KEY (codigo_lote)\n"
                    + ")");

            st.execute("insert into tabela_Lote (lote_lote, descricao_lote) values ('Lote 1','Primeiro Lote')");

            st.execute("CREATE TABLE tabela_categoria (\n"
                    + "  codigo_categoria int(11) NOT NULL AUTO_INCREMENT,\n"
                    + "  categoria_categoria varchar(45) DEFAULT NULL,\n"
                    + "  descricao_categoria varchar(45) DEFAULT NULL,\n"
                    + "  PRIMARY KEY (codigo_categoria)\n"
                    + ")");

            st.execute("insert into tabela_categoria (categoria_categoria, descricao_categoria) values ('Infantil','Categoria Infantil')");
            st.execute("insert into tabela_categoria (categoria_categoria, descricao_categoria) values ('Bebê','Categoria Bebê')");
            st.execute("insert into tabela_categoria (categoria_categoria, descricao_categoria) values ('Adulto','Categoria Adulto')");
            st.execute("insert into tabela_categoria (categoria_categoria, descricao_categoria) values ('3 idade','Categoria 3 idade')");

            st.execute("CREATE TABLE tabela_baixa_estoque (\n"
                    + "  codigo_be int(11) NOT NULL AUTO_INCREMENT,\n"
                    + "  nome_be varchar(45) DEFAULT NULL,\n"
                    + "  descricao_be varchar(45) DEFAULT NULL,\n"
                    + "  tamanho_be varchar(45) DEFAULT NULL,\n"
                    + "  valor_be double DEFAULT NULL,\n"
                    + "  lote_be varchar(45) DEFAULT NULL,\n"
                    + "  tipo_be varchar(45) DEFAULT NULL,\n"
                    + "  categoria_be varchar(45) DEFAULT NULL,\n"
                    + "  data_be date DEFAULT NULL,\n"
                    + "  PRIMARY KEY (codigo_be)\n"
                    + ")");

            JOptionPane.showMessageDialog(null, "Criação de banco executado com sucesso!");
            
        } catch (SQLException sqlError) {
            JOptionPane.showMessageDialog(null, "Erro ao criar banco. Contacte o desenvolvedor.");
            throw new RuntimeException(sqlError);
        }


    }//GEN-LAST:event_btCriarBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriacaoBancoDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriacaoBancoDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriacaoBancoDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriacaoBancoDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriacaoBancoDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriarBanco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
