/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cde.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author alafaria
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public String usuarioLogado;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setIconImage(getToolkit().createImage(getClass().getResource("/icones/stock.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/fundo.jpg"));
        Image image = icon.getImage();
        painelDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0,0,getWidth(),getHeight(), this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProduto = new javax.swing.JMenu();
        subMenuCadastrarProduto = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuItensBazar = new javax.swing.JMenu();
        submenuCadastrarTamanho = new javax.swing.JMenuItem();
        submenuCadastrarTipo = new javax.swing.JMenuItem();
        submenuCadastrarCategoria = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        submenuInserirLote = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        submenuConsultarEstoque = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        submenuCriarNovoUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        submenuTrocarUsuario = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Estoque");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuário logado:");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelDesktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDesktopLayout.createSequentialGroup()
                .addGap(0, 499, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuProduto.setForeground(new java.awt.Color(0, 0, 153));
        menuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/produto.png"))); // NOI18N
        menuProduto.setText("Produtos");
        menuProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        subMenuCadastrarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        subMenuCadastrarProduto.setText("Cadastrar Produto");
        subMenuCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastrarProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(subMenuCadastrarProduto);

        jMenuItem7.setText("Consultar Produtos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuProduto.add(jMenuItem7);

        jMenuBar1.add(menuProduto);

        menuItensBazar.setForeground(new java.awt.Color(0, 0, 153));
        menuItensBazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/itens.png"))); // NOI18N
        menuItensBazar.setText("Itens de Bazar");
        menuItensBazar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        submenuCadastrarTamanho.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        submenuCadastrarTamanho.setText("Cadastrar Tamanho");
        submenuCadastrarTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuCadastrarTamanhoActionPerformed(evt);
            }
        });
        menuItensBazar.add(submenuCadastrarTamanho);

        submenuCadastrarTipo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        submenuCadastrarTipo.setText("Cadastrar Tipo");
        submenuCadastrarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuCadastrarTipoActionPerformed(evt);
            }
        });
        menuItensBazar.add(submenuCadastrarTipo);

        submenuCadastrarCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        submenuCadastrarCategoria.setText("Cadastrar Categoria");
        submenuCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuCadastrarCategoriaActionPerformed(evt);
            }
        });
        menuItensBazar.add(submenuCadastrarCategoria);
        menuItensBazar.add(jSeparator1);

        submenuInserirLote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        submenuInserirLote.setText("Inserir Lote");
        submenuInserirLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuInserirLoteActionPerformed(evt);
            }
        });
        menuItensBazar.add(submenuInserirLote);

        jMenuBar1.add(menuItensBazar);

        menuEstoque.setForeground(new java.awt.Color(0, 0, 153));
        menuEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/stock.png"))); // NOI18N
        menuEstoque.setText("Estoque");
        menuEstoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem6.setText("Controle de Estoque");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuEstoque.add(jMenuItem6);

        submenuConsultarEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        submenuConsultarEstoque.setText("Consultar baixa de estoque");
        submenuConsultarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuConsultarEstoqueActionPerformed(evt);
            }
        });
        menuEstoque.add(submenuConsultarEstoque);

        jMenuBar1.add(menuEstoque);

        jMenu1.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/relatorio.png"))); // NOI18N
        jMenu1.setText("Consultas");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem2.setText("Consulta Por Lote");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Consulta Por Tamanho");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Consulta Por Categoria");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Consulta Por Tipo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        menuUsuario.setForeground(new java.awt.Color(0, 0, 153));
        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/usuario.png"))); // NOI18N
        menuUsuario.setText("Usuário");
        menuUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        submenuCriarNovoUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        submenuCriarNovoUsuario.setText("Criar novo usuário");
        submenuCriarNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuCriarNovoUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(submenuCriarNovoUsuario);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("ConsultarUsuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem1);

        submenuTrocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        submenuTrocarUsuario.setText("Trocar de Usuário");
        submenuTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuTrocarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(submenuTrocarUsuario);

        jMenuBar1.add(menuUsuario);

        menuSair.setForeground(new java.awt.Color(0, 0, 153));
        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setExtendedState(this.MAXIMIZED_BOTH);

        labelUsuario.setText(usuarioLogado);

        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void submenuTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuTrocarUsuarioActionPerformed
        // TODO add your handling code here:
        TelaLogin telaLogin = new TelaLogin();
        this.dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_submenuTrocarUsuarioActionPerformed

    private void submenuCriarNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuCriarNovoUsuarioActionPerformed
        // TODO add your handling code here:
        TelaCadastroUsuario telaCadastroUsuario = new TelaCadastroUsuario();
        telaCadastroUsuario.setVisible(true);
    }//GEN-LAST:event_submenuCriarNovoUsuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaCadastroUsuario telaCadastroUsuário = new TelaCadastroUsuario();
        telaCadastroUsuário.painelUsuario.setSelectedIndex(1);
        telaCadastroUsuário.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void submenuCadastrarTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuCadastrarTamanhoActionPerformed
        // TODO add your handling code here:
        TelaCadastroTamanho telaTamanho = new TelaCadastroTamanho();
        telaTamanho.setVisible(true);

    }//GEN-LAST:event_submenuCadastrarTamanhoActionPerformed

    private void submenuCadastrarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuCadastrarTipoActionPerformed
        // TODO add your handling code here:
        TelaCadastroTipo telaTipo = new TelaCadastroTipo();
        telaTipo.setVisible(true);

    }//GEN-LAST:event_submenuCadastrarTipoActionPerformed

    private void submenuCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuCadastrarCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCadastroCategoria telaCategoria = new TelaCadastroCategoria();
        telaCategoria.setVisible(true);
    }//GEN-LAST:event_submenuCadastrarCategoriaActionPerformed

    private void submenuInserirLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuInserirLoteActionPerformed
        // TODO add your handling code here:
        TelaCadastroLote telaLote = new TelaCadastroLote();
        telaLote.setVisible(true);
    }//GEN-LAST:event_submenuInserirLoteActionPerformed

    private void subMenuCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        TelaCadastroProdutos telaProdutos = new TelaCadastroProdutos();
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_subMenuCadastrarProdutoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TelaConsultaLote telaConsultaLote = new TelaConsultaLote();
        telaConsultaLote.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        TelaConsultaTamanho telaConsultaTamanho = new TelaConsultaTamanho();
        telaConsultaTamanho.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        TelaConsultaCategoria tcc = new TelaConsultaCategoria();
        tcc.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        TelaConsultaTipo tct = new TelaConsultaTipo();
        tct.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void submenuConsultarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuConsultarEstoqueActionPerformed
        // TODO add your handling code here:
        TelaConsultaBaixaEstoque tcbe = new TelaConsultaBaixaEstoque();
        tcbe.setVisible(true);
    }//GEN-LAST:event_submenuConsultarEstoqueActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        TelaConsultaControleEstoque tcce = new TelaConsultaControleEstoque();
        tcce.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        TelaCadastroProdutos telaCadastroProdutos = new TelaCadastroProdutos();
        telaCadastroProdutos.jTabbedProduto.setSelectedIndex(1);
        telaCadastroProdutos.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JLabel labelUsuario;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenu menuItensBazar;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu menuSair;
    public javax.swing.JMenu menuUsuario;
    private javax.swing.JDesktopPane painelDesktop;
    private javax.swing.JMenuItem subMenuCadastrarProduto;
    public javax.swing.JMenuItem submenuCadastrarCategoria;
    public javax.swing.JMenuItem submenuCadastrarTamanho;
    public javax.swing.JMenuItem submenuCadastrarTipo;
    private javax.swing.JMenuItem submenuConsultarEstoque;
    private javax.swing.JMenuItem submenuCriarNovoUsuario;
    public javax.swing.JMenuItem submenuInserirLote;
    private javax.swing.JMenuItem submenuTrocarUsuario;
    // End of variables declaration//GEN-END:variables
}
