/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cde.view;

import br.com.cde.dao.BaixaEstoqueDAO;
import br.com.cde.dao.CategoriaDAO;
import br.com.cde.dao.LoteDAO;
import br.com.cde.dao.ProdutoDAO;
import br.com.cde.dao.TamanhoDAO;
import br.com.cde.dao.TipoDAO;
import br.com.cde.model.BaixaEstoque;
import br.com.cde.model.Categoria;
import br.com.cde.model.Lote;
import br.com.cde.model.Produtos;
import br.com.cde.model.Tamanho;
import br.com.cde.model.Tipo;
import br.com.cde.tableModel.TabelaModeloProduto;
import br.com.cde.utilitarios.SomenteNumeros;
import br.com.cde.utilitarios.Utilitarios;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author alafaria
 */
public class TelaConsultaControleEstoque extends javax.swing.JFrame {

    Utilitarios utilitarios = new Utilitarios();
    
    /**
     * Creates new form TelaConsultaControleEstoque
     */
    public TelaConsultaControleEstoque() {
        initComponents();
        setIconImage(getToolkit().createImage(getClass().getResource("/icones/stock.png")));
        tabelaConsultaEstoque.setModel(new TabelaModeloProduto(new ProdutoDAO().listarProdutos()));
        txtAddEstoque.setDocument(new SomenteNumeros());
        txtRetirarEstoque.setDocument(new SomenteNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedConsultaEstoque = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisarItem = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        comboTipo = new javax.swing.JComboBox<>();
        btPesquisarTipo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        comboTamanho = new javax.swing.JComboBox<>();
        btPesquisarTamanho = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        comboCategoria = new javax.swing.JComboBox<>();
        btPesquisarCategoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsultaEstoque = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        comboLote = new javax.swing.JComboBox<>();
        btPesquisarLote = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtAddEstoque = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRetirarEstoque = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        btAdicionarQuantidade = new javax.swing.JButton();
        btRetirarQuantidade = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Estoque");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Controle de Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        jLabel2.setText("Consultar Item:");

        txtPesquisarItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPesquisarItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarItemKeyPressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Por Tipo"));

        comboTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboTipo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboTipoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btPesquisarTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btPesquisarTipo.setText("Pesquisar");
        btPesquisarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPesquisarTipo)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisarTipo)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Por Tamanho"));

        comboTamanho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboTamanho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboTamanhoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btPesquisarTamanho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btPesquisarTamanho.setText("Pesquisar");
        btPesquisarTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarTamanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPesquisarTamanho)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisarTamanho)
                    .addComponent(comboTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Por Categoria"));

        comboCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboCategoria.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboCategoriaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btPesquisarCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btPesquisarCategoria.setText("Pesquisar");
        btPesquisarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPesquisarCategoria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisarCategoria)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tabelaConsultaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaConsultaEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaConsultaEstoque);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Por Lote"));

        comboLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboLote.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboLoteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btPesquisarLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btPesquisarLote.setText("Pesquisar");
        btPesquisarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboLote, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPesquisarLote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisarLote)
                    .addComponent(comboLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPesquisarItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedConsultaEstoque.addTab("ConsultarEstoque", jPanel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Adicionar ao estoque:");

        txtAddEstoque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Retirar do estoque:");

        txtRetirarEstoque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor: R$");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantidade:");

        txtQuantidade.setEditable(false);
        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome Produto:");

        txtNomeProduto.setEditable(false);
        txtNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Código:");

        txtValor.setEditable(false);
        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Descrição:");

        txtDescricao.setEditable(false);
        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tamanho:");

        txtTamanho.setEditable(false);
        txtTamanho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Lote:");

        txtLote.setEditable(false);
        txtLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTipo.setEditable(false);
        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tipo:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Categoria:");

        txtCategoria.setEditable(false);
        txtCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(txtLote)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel10)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btAdicionarQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAdicionarQuantidade.setText("Adicionar");
        btAdicionarQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarQuantidadeActionPerformed(evt);
            }
        });

        btRetirarQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btRetirarQuantidade.setText("Retirar");
        btRetirarQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetirarQuantidadeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Consultar Baixa de Produtos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/carrinho.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRetirarEstoque)
                                    .addComponent(txtAddEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAdicionarQuantidade)
                                    .addComponent(btRetirarQuantidade, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(303, 303, 303))))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAdicionarQuantidade, btRetirarQuantidade});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAddEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAdicionarQuantidade))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtRetirarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRetirarQuantidade))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel14)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAdicionarQuantidade, btRetirarQuantidade});

        jTabbedConsultaEstoque.addTab("Baixa de Estoque", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedConsultaEstoque)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedConsultaEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarItemKeyPressed
        // TODO add your handling code here:
        String pesquisar = txtPesquisarItem.getText();
        tabelaConsultaEstoque.setModel(new TabelaModeloProduto(new ProdutoDAO().listarProdutoPorNome(pesquisar)));
    }//GEN-LAST:event_txtPesquisarItemKeyPressed

    private void comboLoteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboLoteAncestorAdded
        // TODO add your handling code here:
        comboLote.removeAllItems();
        LoteDAO loteDAO = new LoteDAO();
        List<Lote> listaDeLote = loteDAO.listarLote();
        
        for (Lote l : listaDeLote) {
            comboLote.addItem(String.valueOf(l));
        }
    }//GEN-LAST:event_comboLoteAncestorAdded

    private void btPesquisarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarLoteActionPerformed
        // TODO add your handling code here:
        String pesquisar = (String) comboLote.getSelectedItem();
        tabelaConsultaEstoque.setModel(new TabelaModeloProduto(new ProdutoDAO().listarProdutosPorLote(pesquisar)));
    }//GEN-LAST:event_btPesquisarLoteActionPerformed

    private void comboTipoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboTipoAncestorAdded
        // TODO add your handling code here:
        comboTipo.removeAllItems();
        TipoDAO tipoDAO = new TipoDAO();
        List<Tipo> listaDeTipo = tipoDAO.listarTipo();
        
        for (Tipo t : listaDeTipo) {
            comboTipo.addItem(String.valueOf(t));
        }
    }//GEN-LAST:event_comboTipoAncestorAdded

    private void btPesquisarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarTipoActionPerformed
        // TODO add your handling code here:
        String pesquisar = (String) comboTipo.getSelectedItem();
        tabelaConsultaEstoque.setModel(new TabelaModeloProduto(new ProdutoDAO().listarProdutosPorTipo(pesquisar)));
    }//GEN-LAST:event_btPesquisarTipoActionPerformed

    private void comboTamanhoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboTamanhoAncestorAdded
        // TODO add your handling code here:
        comboTamanho.removeAllItems();
        TamanhoDAO tamanhoDAO = new TamanhoDAO();
        List<Tamanho> listaDeTamanho = tamanhoDAO.listarTamanho();
        
        for (Tamanho tam : listaDeTamanho) {
            comboTamanho.addItem(String.valueOf(tam));
        }
    }//GEN-LAST:event_comboTamanhoAncestorAdded

    private void comboCategoriaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboCategoriaAncestorAdded
        // TODO add your handling code here:
        comboCategoria.removeAllItems();
        CategoriaDAO categoriaDAO = new CategoriaDAO();
        List<Categoria> listaDeCategoria = categoriaDAO.listarCategoria();
        
        for (Categoria c : listaDeCategoria) {
            comboCategoria.addItem(String.valueOf(c));
        }
    }//GEN-LAST:event_comboCategoriaAncestorAdded

    private void btPesquisarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCategoriaActionPerformed
        // TODO add your handling code here:
        String pesquisar = (String) comboCategoria.getSelectedItem();
        tabelaConsultaEstoque.setModel(new TabelaModeloProduto(new ProdutoDAO().listarProdutosPorCategoria(pesquisar)));
    }//GEN-LAST:event_btPesquisarCategoriaActionPerformed

    private void btPesquisarTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarTamanhoActionPerformed
        // TODO add your handling code here:
        String pesquisar = (String) comboTamanho.getSelectedItem();
        tabelaConsultaEstoque.setModel(new TabelaModeloProduto(new ProdutoDAO().listarProdutosPorTamanho(pesquisar)));
    }//GEN-LAST:event_btPesquisarTamanhoActionPerformed

    private void btAdicionarQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarQuantidadeActionPerformed
        // TODO add your handling code here:
        if (txtAddEstoque.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo adicionar estoque em branco!");
        } else {
            int quantidade = Integer.parseInt(txtQuantidade.getText());
            int quantidade2 = Integer.parseInt(txtAddEstoque.getText());
            int resultado = quantidade + quantidade2;

            Produtos produto = new Produtos();
            txtQuantidade.setText(Integer.toString(resultado));
            produto.setCodigoProduto(Integer.parseInt(txtCodigo.getText()));
            produto.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            ProdutoDAO dao = new ProdutoDAO();
            dao.incluirQuantidade(produto);

            tabelaConsultaEstoque.setModel(new TabelaModeloProduto(new ProdutoDAO().listarProdutos()));
            txtAddEstoque.setText("");

            jTabbedConsultaEstoque.setSelectedIndex(0);
        }

    }//GEN-LAST:event_btAdicionarQuantidadeActionPerformed

    private void tabelaConsultaEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaEstoqueMouseClicked
        // TODO add your handling code here:
        jTabbedConsultaEstoque.setSelectedIndex(1);
        txtCodigo.setText(tabelaConsultaEstoque.getValueAt(tabelaConsultaEstoque.getSelectedRow(), TabelaModeloProduto.COLUNA_CODIGO_PRODUTO).toString());
        txtNomeProduto.setText(tabelaConsultaEstoque.getValueAt(tabelaConsultaEstoque.getSelectedRow(), TabelaModeloProduto.COLUNA_NOME_PRODUTO).toString());
        txtDescricao.setText(tabelaConsultaEstoque.getValueAt(tabelaConsultaEstoque.getSelectedRow(), TabelaModeloProduto.COLUNA_DESCRICAO_PRODUTO).toString());
        txtTamanho.setText(tabelaConsultaEstoque.getValueAt(tabelaConsultaEstoque.getSelectedRow(), TabelaModeloProduto.COLUNA_TAMANHO_PRODUTO).toString());
        txtValor.setText(tabelaConsultaEstoque.getValueAt(tabelaConsultaEstoque.getSelectedRow(), TabelaModeloProduto.COLUNA_VALOR_PRODUTO).toString());
        txtLote.setText(tabelaConsultaEstoque.getValueAt(tabelaConsultaEstoque.getSelectedRow(), TabelaModeloProduto.COLUNA_LOTE_PRODUTO).toString());
        txtTipo.setText(tabelaConsultaEstoque.getValueAt(tabelaConsultaEstoque.getSelectedRow(), TabelaModeloProduto.COLUNA_TIPO_PRODUTO).toString());
        txtCategoria.setText(tabelaConsultaEstoque.getValueAt(tabelaConsultaEstoque.getSelectedRow(), TabelaModeloProduto.COLUNA_CATEGORIA_PRODUTO).toString());
        txtQuantidade.setText(tabelaConsultaEstoque.getValueAt(tabelaConsultaEstoque.getSelectedRow(), TabelaModeloProduto.COLUNA_QUANTIDADE_PRODUTO).toString());
    }//GEN-LAST:event_tabelaConsultaEstoqueMouseClicked

    private void btRetirarQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetirarQuantidadeActionPerformed
        // TODO add your handling code here:
        if (txtRetirarEstoque.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo retirar estoque em branco!");
        } else {
            int quantidade = Integer.parseInt(txtQuantidade.getText());
            int quantidade2 = Integer.parseInt(txtRetirarEstoque.getText());
            int resultado = quantidade - quantidade2;

            Produtos produto = new Produtos();

            if (resultado == 0) {
                txtRetirarEstoque.setText("0");
                produto.setCodigoProduto(Integer.parseInt(txtCodigo.getText()));
                produto.setQuantidade(Integer.parseInt(txtRetirarEstoque.getText()));
                ProdutoDAO dao = new ProdutoDAO();
                dao.decrementarQuantidade(produto);

                BaixaEstoque baixaEstoque = new BaixaEstoque();
                baixaEstoque.setNome(txtNomeProduto.getText());
                baixaEstoque.setDescricao(txtDescricao.getText());
                baixaEstoque.setTamanho(comboTamanho.getSelectedItem().toString());
                baixaEstoque.setValor(Double.parseDouble(txtValor.getText()));
                baixaEstoque.setLote(comboLote.getSelectedItem().toString());
                baixaEstoque.setTipo(comboTipo.getSelectedItem().toString());
                baixaEstoque.setCategoria(comboCategoria.getSelectedItem().toString());

                BaixaEstoqueDAO bDao = new BaixaEstoqueDAO();
                bDao.cadastrarProdutoBaixa(baixaEstoque);

                produto.setCodigoProduto(Integer.parseInt(txtCodigo.getText()));
                dao.excluirProdutoDeBaixa(produto);
                
                tabelaConsultaEstoque.setModel(new TabelaModeloProduto(new ProdutoDAO().listarProdutos()));

                utilitarios.limpaTela(jPanel2);
                
            } else if (resultado < 0) {
                JOptionPane.showMessageDialog(null, "Não é possivel retirar do estoque a quantidade estipulada");

            } else {
                txtRetirarEstoque.setText(Integer.toString(resultado));
                produto.setCodigoProduto(Integer.parseInt(txtCodigo.getText()));
                produto.setQuantidade(Integer.parseInt(txtRetirarEstoque.getText()));
                ProdutoDAO dao = new ProdutoDAO();
                dao.decrementarQuantidade(produto);
            }

            tabelaConsultaEstoque.setModel(new TabelaModeloProduto(new ProdutoDAO().listarProdutos()));
            txtRetirarEstoque.setText("");

            jTabbedConsultaEstoque.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btRetirarQuantidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaConsultaBaixaEstoque tcbe = new TelaConsultaBaixaEstoque();
        tcbe.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaControleEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarQuantidade;
    private javax.swing.JButton btPesquisarCategoria;
    private javax.swing.JButton btPesquisarLote;
    private javax.swing.JButton btPesquisarTamanho;
    private javax.swing.JButton btPesquisarTipo;
    private javax.swing.JButton btRetirarQuantidade;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboLote;
    private javax.swing.JComboBox<String> comboTamanho;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedConsultaEstoque;
    private javax.swing.JTable tabelaConsultaEstoque;
    private javax.swing.JTextField txtAddEstoque;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPesquisarItem;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtRetirarEstoque;
    private javax.swing.JTextField txtTamanho;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
